### ISSUE TITLE
Backend Modelo de datos

### ISSUE THREAD

**Issue by Jmofuture** [4GeeksAcademy/Grupo1_Proyecto_Final_4Geeks#3]

**Comment by Jmofuture** [comment]
Modelo de datos Academia de Manejo

**Comment by josecaro02** [comment]
![Image](https://github.com/user-attachments/assets/b94e292a-7654-4b1d-8619-377b5b92f6db)

**Comment by Jmofuture** [comment]
![Diagram 1 (1)](https://github.com/user-attachments/assets/80163d62-3073-41d0-881a-a98f9b6a3a9b)

**Comment by Jmofuture** [comment]
![Image](https://github.com/user-attachments/assets/df59058d-03fd-4287-b22e-15c863f2eaeb)

**Comment by Jmofuture** [comment]
![Image](https://github.com/user-attachments/assets/efa57858-68f4-4744-a21a-c0c134dea789)

**Comment by Jmofuture** [comment]
![Image](https://github.com/user-attachments/assets/36174bb2-5af7-4737-87ee-96c3adb3cba8)
